server:
    port: 3000
spring:
    application:
        name: enter-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
        nacos:
            discovery:
                server-addr: localhost:8848
                group: SPARKS-A

logging:
    level:
        root: info
    pattern:
      console: '%clr(%5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

