server:
  port: 3002

spring:
  application:
    name: enter-user-biz
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: #设置白名单 为空允许所有访问
        url-pattern: /druid/*
        login-username:   #控制台用户名/密码
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

      initial-size: 5 # 初始连接数
      min-idle: 10 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
      validation-query: SELECT 1 FROM DUAL # 配置检测连接是否有效
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      url: jdbc:mysql://localhost:3307/enter_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      username: root
      password: 123456


feign:
  httpclient:
    enabled: true
  sentinel:
    enabled: on # openfeign 和 sentinel 的整合

ribbon:
  ReadTimeout: 1000   # 请求处理的超时时间，默认值 5000
  MaxAutoRetries: 2   # 最大重试次数，默认值 0
  MaxAutoRetriesNextServer: 0    # 切换实例的重试次数，默认值 1
  OkToRetryOnAllOperations: true    # 默认 false 表示重试设置只对 GET 请求生效
  eager-load:
    enabled: true
    clients: enter-admin-biz

#logging:
#    level:
#        cool.sparks.enteradmin.api.http: DEBUG

enter:
  info:
    version: 1.0
    base-package: cool.sparks.user
  open-api:
    title: 用户管理N
    description: 用户管理Api
    termsOfServiceUrl: /doc.html
    author: Sparks
    pageUrl: sparks.cool
    email: guipengzai@gmail.com
    version: ${enter.info.version}
    groupName: ${spring.application.name}
    base-package: ${enter.info.base-package}
    enable: true

